name: Publish crate

on:
  push:
    tags:
      - "lib-v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Publish to crates.io
        working-directory: lib
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
