name: Release CLI

on:
  push:
    tags:
      - "cli-v*"

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build binary
        run: cargo build --release --package bedrockci-cli
      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/bedrockci
